# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dice_roll.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dice_roll.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x64ice_roll.proto\"+\n\x08\x44iceRoll\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DICEROLL = _descriptor.Descriptor(
  name='DiceRoll',
  full_name='DiceRoll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DiceRoll.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='DiceRoll.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['DiceRoll'] = _DICEROLL

DiceRoll = _reflection.GeneratedProtocolMessageType('DiceRoll', (_message.Message,), dict(
  DESCRIPTOR = _DICEROLL,
  __module__ = 'dice_roll_pb2'
  # @@protoc_insertion_point(class_scope:DiceRoll)
  ))
_sym_db.RegisterMessage(DiceRoll)


# @@protoc_insertion_point(module_scope)
