/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Wed Apr  4 14:54:33 2018. */

#include "dice_roll.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DiceRoll_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, DiceRoll, message, message, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, DiceRoll, number, message, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
